@startuml

' Установка стилей для сущностей
skinparam entityStyle rectangular
skinparam entityFontColor black
skinparam entityAttributeFontColor black

' Определение сущностей (Entities)
entity "Справочник.ТочкиДоступа" as ТочкиДоступа {
    +ИмяПредопределенныхДанных
    Предопределенный
    Ссылка
    ПометкаУдаления
    Наименование
    Код
}

entity "Справочник.ОбъектыДоступа" as ОбъектыДоступа {
    +ИмяПредопределенныхДанных
    Предопределенный
    Ссылка
    ПометкаУдаления
    Наименование
    Код
    Телефон
    Должность
    Отдел
    ТабельныйНомер
}

entity "Справочник.Должность" as Должность {
    +ИмяПредопределенныхДанных
    Предопределенный
    Ссылка
    ПометкаУдаления
    Наименование
    Код
}

entity "Справочник.Отдел" as Отдел {
    +ИмяПредопределенныхДанных
    Предопределенный
    Ссылка
    ПометкаУдаления
    Наименование
    Код
}

entity "Справочник.Подключение" as Подключение {
    +ИмяПредопределенныхДанных
    Предопределенный
    Ссылка
    ПометкаУдаления
    Наименование
    Код
    Адрес
    Порт
    Логин
    Пароль
    ВиртуальныйХост
    ТочкаОбмена
    ИмяОчереди
    КлючМаршрутизации
}

entity "Документ.ДокументСписокНарушителей" as ДокументСписокНарушителей {
    Проведен
    Ссылка
    ПометкаУдаления
    Дата
    Номер
    Отдел
    ТабличнаяЧасть
    Объект
    Направление
}

entity "Перечисление.НаправленияПрохода" as НаправленияПрохода {
    Вход
    Выход
}

entity "РегистрСведений.ЖурналСобытий" as ЖурналСобытий {
    Период
    ДатаСобытия
    ОбъектДоступа
    ТочкаДоступа
    Направление
    ГосНомера
    ВремяСобытия
}

' Связи между сущностями (Relationships)
ДокументСписокНарушителей --> Отдел : "Отдел (1:N)"
ОбъектыДоступа --> ДокументСписокНарушителей : "Объект (1:N)"
ОбъектыДоступа --> ЖурналСобытий : "ОбъектДоступа (1:N)"
ТочкиДоступа --> ЖурналСобытий : "ТочкаДоступа (1:N)"
НаправленияПрохода --> ДокументСписокНарушителей : "Направление (1:N)"
НаправленияПрохода --> ЖурналСобытий : "Направление (1:N)"
Отдел --> ОбъектыДоступа : "Должность (1:N)"
Отдел --> ДокументСписокНарушителей : "Отдел (1:N)"
Должность --> ОбъектыДоступа : "Должность (1:N)"
Подключение --> ТочкиДоступа : "ТочкаОбмена (1:N)"

@enduml
